const app=document.querySelector('#app'),live=document.querySelector('#live'),toast=document.querySelector('#toast');
const initial=()=>({route:'picker',parent:false,child:null,children:[{id:'leo',name:'Leo',avatar:'🐼',points:42}],habit:null,status:'not_started',reason:'',networkFail:false,approving:false,reversed:false,reportPeriod:'week'});
let s=initial();
const esc=v=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function announce(msg){live.textContent='';setTimeout(()=>live.textContent=msg,20);toast.textContent=msg;toast.hidden=false;setTimeout(()=>toast.hidden=true,2600)}
function go(route){s.route=route;render();requestAnimationFrame(()=>document.querySelector('h1')?.focus())}
function header(title,back){return `<header class="topbar">${back?`<button class="text-button" data-go="${back}">← Back</button>`:'<span class="brand">Habit Home</span>'}<span class="muted">Good habit starts from home</span></header><main id="main"><h1 tabindex="-1">${title}</h1>`}
function parentNav(){return `<aside class="sidebar"><strong>Parent Mode</strong>${[['dashboard','Overview'],['approvals','Approvals'],['habit','Habits'],['children','Children'],['reports','Reports'],['points','Points']].map(x=>`<button data-go="${x[0]}">${x[1]}</button>`).join('')}<button data-action="exit">Exit Parent Mode</button></aside>`}
function render(){let html='';
 if(s.route==='picker') html=picker();
 else if(s.route==='unlock') html=unlock();
 else if(['dashboard','approvals','children','child-form','habit','points','reports'].includes(s.route)){if(!s.parent) html=permission();else html=parentPage()}
 else if(s.route==='today'||s.route==='detail'||s.route==='child-points'){if(!s.child) html=permission();else html=childPage()}
 else html=permission(); app.innerHTML=html; bind();}
function picker(){return `<div class="shell">${header('Who is using Habit Home?')}</main><div class="hero"><p>Select a profile to see today’s habits.</p></div><div class="grid">${s.children.map(c=>`<button class="profile-card" data-child="${c.id}" aria-label="Continue as ${esc(c.name)}"><span class="avatar">${c.avatar}</span><strong>${esc(c.name)}</strong></button>`).join('')||'<div class="card"><p>No child profiles yet.</p></div>'}</div><div class="parent-entry"><button data-go="unlock">🔒 Parent Mode</button></div></div>`}
function unlock(){return `<div class="shell">${header('Unlock Parent Mode','picker')}<form class="form card" id="unlock-form"><div class="field"><label for="pin">6-digit parent PIN</label><input id="pin" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" value="123456" aria-describedby="pin-help"><small id="pin-help">Prototype PIN: 123456</small></div><button>Unlock</button></form></main></div>`}
function permission(){return `<div class="shell">${header('This page is not available')}<div class="permission"><div class="avatar">🔒</div><p>This profile does not have permission to view that page, or it no longer exists.</p><button data-action="exit">Return to profile picker</button></div></main></div>`}
function parentPage(){let body='';if(s.route==='dashboard')body=dashboard();if(s.route==='approvals')body=approvals();if(s.route==='children')body=children();if(s.route==='child-form')body=childForm();if(s.route==='habit')body=habitForm();if(s.route==='points')body=points();if(s.route==='reports')body=reports();return `<div class="shell parent">${parentNav()}<section class="parent-main">${body}<nav class="bottom-nav" aria-label="Parent navigation"><button data-go="dashboard">Home</button><button data-go="approvals">Approvals</button><button data-go="habit">Tasks</button><button data-go="children">More</button></nav></section></div>`}
function dashboard(){let pending=s.status==='pending'?1:0;return `${header('Family overview')}<p>Friday, 7 August · Asia/Jakarta</p><div class="card"><h2>${pending} waiting for approval</h2>${pending?'<button data-go="approvals">Review now</button>':'<p class="muted">You’re all caught up.</p>'}</div><h2>Today</h2><div class="grid">${s.children.map(c=>`<article class="card"><span class="avatar">${c.avatar}</span><h3>${esc(c.name)}</h3><p>${c.id==='maya'&&s.status==='approved'?'1 of 1 done':'0 done'} · ${c.id==='maya'&&pending?'1 waiting':'reviewed'}</p></article>`).join('')}</div><div class="actions"><button data-go="habit">+ Add habit or task</button><button class="secondary" data-go="children">Manage children</button><button class="secondary" data-go="reports">View reports</button></div></main>`}
function approvals(){if(s.status!=='pending')return `${header('Approvals','dashboard')}<div class="card"><div class="avatar">✓</div><h2>Nothing waiting</h2><p>New child submissions will appear here.</p></div></main>`;return `${header('Approvals · 1 waiting','dashboard')}<article class="card" id="approval-card"><p class="eyebrow">🦊 Maya</p><h2>${esc(s.habit?.title||'Read for 15 minutes')}</h2><p>Sent just now · ${s.habit?.points||10} points</p><div class="actions"><button class="secondary" data-action="reject">Not yet</button><button data-action="approve" ${s.approving?'disabled':''}>${s.approving?'Approving…':`Approve · +${s.habit?.points||10}`}</button></div></article></main>`}
function children(){return `${header('Children','dashboard')}<div class="stack">${s.children.map(c=>`<article class="card task-card"><div><span>${c.avatar}</span> <strong>${esc(c.name)}</strong><p class="muted">${c.points} points · PIN off</p></div><button class="secondary" aria-label="Edit ${esc(c.name)}">Edit</button></article>`).join('')}</div><button data-go="child-form">+ Add child</button></main>`}
function childForm(){return `${header('Add child','children')}<form class="form card" id="child-form"><div class="field"><label for="name">Nickname</label><input id="name" required value="Maya"></div><fieldset><legend class="legend">Choose an avatar</legend><div class="choice-row">${['🦊','🐻','🐰','🦉','🐱','🐘','🐼','🐨'].map((a,i)=>`<button type="button" class="choice" data-avatar="${a}" aria-pressed="${i===0}">${a}<span class="sr-only">${['Fox','Bear','Rabbit','Owl','Cat','Elephant','Panda','Koala'][i]}</span></button>`).join('')}</div></fieldset><div class="field"><label for="child-pin">Child PIN (optional)</label><input id="child-pin" inputmode="numeric" maxlength="6"></div><button>Save child</button></form></main>`}
function habitForm(){let hasMaya=s.children.some(c=>c.id==='maya');return `${header('New habit','dashboard')}<form class="form card" id="habit-form"><div class="choice-row" role="group" aria-label="Assignment type"><button type="button" class="choice" aria-pressed="true">Recurring</button><button type="button" class="choice" aria-pressed="false">One-off</button></div><div class="field"><label for="title">Title</label><input id="title" required value="Read for 15 minutes"></div><div class="field"><label for="description">Description</label><textarea id="description">Choose a book and read for 15 minutes.</textarea></div><fieldset><legend class="legend">Who</legend>${hasMaya?'<label><input type="checkbox" id="assign-maya" checked> 🦊 Maya</label>':'<p class="notice error">Add Maya first, then return to create her habit.</p>'}</fieldset><div class="field"><label for="points">Points</label><input id="points" type="number" min="1" max="10000" value="10"></div><fieldset><legend class="legend">Schedule</legend><label><input type="radio" name="schedule"> Every day</label><label><input type="radio" name="schedule" checked> Selected days</label><div class="choice-row" aria-label="Selected weekdays">${['M','T','W','T','F','S','S'].map((d,i)=>`<button type="button" class="choice" aria-pressed="${i<5}">${d}</button>`).join('')}</div></fieldset><p class="notice">Summary: Maya · Weekdays · 10 points · starts 7 Aug 2026</p><button ${hasMaya?'':'disabled'}>Save habit</button></form></main>`}
function points(){return `${header('Points','dashboard')}<div class="grid">${s.children.map(c=>`<article class="card"><span class="avatar">${c.avatar}</span><h2>${esc(c.name)}</h2><p class="points">${c.points}</p><p>points</p>${c.id==='maya'&&s.status==='approved'&&!s.reversed?'<button class="danger" data-action="reverse-open">Reverse latest approval</button>':''}</article>`).join('')}</div></main>`}
function reports(){let approved=s.status==='approved'?1:0,pending=s.status==='pending'?1:0,incomplete=s.habit&&!approved&&!pending?1:0,earned=approved?(s.habit?.points||10):0,periods={day:['7 August 2026','Daily'],week:['2–8 August 2026 · Sunday start','Weekly'],month:['August 2026','Monthly']},selected=periods[s.reportPeriod];return `${header('Child reports','dashboard')}<div class="choice-row" role="group" aria-label="Report period">${['day','week','month'].map(p=>`<button data-period="${p}" aria-pressed="${s.reportPeriod===p}">${p[0].toUpperCase()+p.slice(1)}</button>`).join('')}</div><p><button class="text-button" aria-label="Previous ${s.reportPeriod}">←</button> ${selected[0]} <button class="text-button" aria-label="Next ${s.reportPeriod}">→</button></p><article class="card"><p class="eyebrow">🦊 Maya · Asia/Jakarta</p><h2>${selected[1]} progress</h2><dl class="report-grid"><div><dt>Assigned</dt><dd>${s.habit?1:0}</dd></div><div><dt>Submitted</dt><dd>${approved||pending?1:0}</dd></div><div><dt>Approved</dt><dd>${approved}</dd></div><div><dt>Waiting</dt><dd>${pending}</dd></div><div><dt>Still to do</dt><dd>${incomplete}</dd></div><div><dt>Points earned</dt><dd>${earned}</dd></div></dl></article></main>`}
function childPage(){let c=s.children.find(x=>x.id===s.child),title=s.habit?.title||'Read for 15 minutes',pts=s.habit?.points||10;if(s.route==='detail')return `<div class="shell">${header(title,'today')}<article class="card"><div class="avatar">📚</div><p>Weekday habit</p><p>${esc(s.habit?.description||'Choose a book and read for 15 minutes.')}</p><p><strong>Today · ${pts} points</strong></p>${detailAction()}</article></main></div>`;if(s.route==='child-points')return `<div class="shell">${header(`${esc(c.name)}’s points`,'today')}<div class="card"><p class="points">${c.points}</p><p>Total points</p>${s.status==='approved'?`<p class="notice">+${pts} · ${esc(title)} · Today</p>`:'<p class="muted">Approved habits will appear here.</p>'}</div></main></div>`;return `<div class="shell">${header(`${c.avatar} ${esc(c.name)}’s today`)}<div class="topbar"><p>Friday, 7 August</p><button class="secondary" data-action="exit">Switch profile</button></div><p>${s.status==='approved'?'1 of 1':'0 of 1'} done today</p><div class="progress" aria-label="Today progress"><span style="width:${s.status==='approved'?100:0}%"></span></div>${todayGroups(title,pts)}<nav class="bottom-nav"><button data-go="today">Today</button><button class="secondary" data-go="child-points">My points</button></nav></main></div>`}
function todayGroups(title,pts){let failure=s.networkFail?'<div class="notice error">Could not send completion. Try again. <button data-action="retry">Retry</button></div>':'';if(s.status==='not_started'||s.status==='rejected')return `${failure}${s.reason?`<div class="notice">Ready to try again. Parent note: ${esc(s.reason)}</div>`:''}<h2>To do · 1</h2><article class="card task-card"><div><h3>📚 ${esc(title)}</h3><p>Weekday habit · ${pts} points</p></div><button data-go="detail">Open</button></article><h2>Waiting for parent · 0</h2><h2>Done · 0</h2>`;if(s.status==='pending')return `<h2>To do · 0</h2><h2>Waiting for parent · 1</h2><article class="card task-card"><div><h3>📚 ${esc(title)}</h3><p>Sent just now</p></div><button data-go="detail">Open</button></article><h2>Done · 0</h2>`;if(s.status==='approval_reversed')return `<h2>To do · 0</h2><h2>Waiting for parent · 0</h2><h2>Done · 0</h2><article class="card"><h3>${esc(title)}</h3><p class="notice">A parent reversed this approval. This item is closed and appears only in activity history.</p></article>`;return `<h2>To do · 0</h2><h2>Waiting for parent · 0</h2><h2>Done · 1</h2><article class="card"><h3>✓ ${esc(title)}</h3><p>Nice work! +${pts} points</p></article>`}
function detailAction(){if(s.status==='pending')return '<p class="status">Waiting for a parent</p><button class="secondary" data-action="withdraw">Undo — I’m not finished</button>';if(s.status==='approved')return `<p class="notice">Nice work! +${s.habit?.points||10} points</p>`;return `<div class="actions"><button data-action="submit">I did it</button><button class="secondary" data-action="offline">Simulate offline</button></div>`}
function modal(kind){let html=kind==='reject'?`<div class="modal-backdrop"><form class="dialog" id="reject-form" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><h2 id="dialog-title">Send back for another try?</h2><div class="field"><label for="reason">Child-safe note (optional)</label><textarea id="reason">Please finish the last few pages.</textarea></div><div class="actions"><button type="button" class="secondary" data-action="close-modal">Cancel</button><button>Not yet</button></div></form></div>`:`<div class="modal-backdrop"><form class="dialog" id="reverse-form" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><h2 id="dialog-title">Reverse this approval?</h2><p>This removes the awarded points and permanently closes this occurrence.</p><div class="field"><label for="reason">Reason</label><input id="reason" required value="Approved by mistake"></div><div class="actions"><button type="button" class="secondary" data-action="close-modal">Cancel</button><button class="danger">Reverse approval</button></div></form></div>`;document.body.insertAdjacentHTML('beforeend',html);document.querySelector('.dialog input,.dialog textarea')?.focus()}
function bind(){document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));document.querySelectorAll('[data-child]').forEach(b=>b.onclick=()=>{s.child=b.dataset.child;go('today')});document.querySelector('[data-action="exit"]')?.addEventListener('click',()=>{s.parent=false;s.child=null;history.replaceState(null,'','#');go('picker')});
 document.querySelectorAll('[data-period]').forEach(b=>b.onclick=()=>{s.reportPeriod=b.dataset.period;render()});
 document.querySelector('#unlock-form')?.addEventListener('submit',e=>{e.preventDefault();if(e.target.pin.value==='123456'){s.parent=true;go('dashboard')}else announce('That PIN did not work. Try again.')});
 document.querySelectorAll('[data-avatar]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-avatar]').forEach(x=>x.setAttribute('aria-pressed','false'));b.setAttribute('aria-pressed','true')});
 document.querySelector('#child-form')?.addEventListener('submit',e=>{e.preventDefault();if(!s.children.some(c=>c.id==='maya'))s.children.unshift({id:'maya',name:e.target.querySelector('#name').value,avatar:document.querySelector('[data-avatar][aria-pressed=true]').dataset.avatar,points:35});announce('Maya’s profile was added.');go('children')});
 document.querySelector('#habit-form')?.addEventListener('submit',e=>{e.preventDefault();s.habit={title:e.target.title.value,description:e.target.description.value,points:Number(e.target.points.value)};announce('Habit saved for Maya.');go('dashboard')});
 document.querySelector('[data-action="submit"]')?.addEventListener('click',()=>{if(!s.networkFail&&sessionStorage.failOnce==='yes'){s.networkFail=true;sessionStorage.failOnce='done';announce('Could not send completion. Try again.');go('today')}else{s.networkFail=false;s.status='pending';announce('Completion sent to a parent.');go('today')}});
 document.querySelector('[data-action="offline"]')?.addEventListener('click',()=>{sessionStorage.failOnce='yes';announce('Offline simulation enabled. Select I did it to test retry.')});
 document.querySelector('[data-action="retry"]')?.addEventListener('click',()=>{s.networkFail=false;s.status='pending';announce('Completion sent to a parent.');render()});
 document.querySelector('[data-action="withdraw"]')?.addEventListener('click',()=>{s.status='not_started';announce('Completion withdrawn.');go('today')});
 document.querySelector('[data-action="reject"]')?.addEventListener('click',()=>modal('reject'));document.querySelector('[data-action="approve"]')?.addEventListener('click',e=>{if(s.status!=='pending')return;s.approving=true;e.currentTarget.disabled=true;e.currentTarget.textContent='Approving…';setTimeout(()=>{if(s.status!=='pending')return;s.status='approved';let c=s.children.find(x=>x.id==='maya');c.points+=s.habit?.points||10;announce(`Approved. ${s.habit?.points||10} points added to Maya.`);render()},450)});
 document.querySelector('[data-action="reverse-open"]')?.addEventListener('click',()=>modal('reverse'));}
document.addEventListener('click',e=>{if(e.target.matches('[data-action="close-modal"]'))e.target.closest('.modal-backdrop').remove()});
document.addEventListener('submit',e=>{if(e.target.id==='reject-form'){e.preventDefault();s.reason=e.target.reason.value;s.status='rejected';e.target.closest('.modal-backdrop').remove();announce('Sent back to Maya for another try.');render()}if(e.target.id==='reverse-form'){e.preventDefault();let c=s.children.find(x=>x.id==='maya');c.points-=s.habit?.points||10;s.reversed=true;s.status='approval_reversed';e.target.closest('.modal-backdrop').remove();announce('Approval reversed and points removed.');render()}});
window.addEventListener('popstate',()=>{if(!s.parent&&['dashboard','approvals','habit','children','points','reports'].includes(s.route))go('picker')});
// Set sessionStorage.failOnce to "yes" in DevTools before submission to review the retry path.
render();
