// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: families.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const childPointBalance = `-- name: ChildPointBalance :one
SELECT coalesce(sum(points), 0)::bigint AS balance
FROM point_ledger WHERE family_id = $1 AND child_id = $2
`

type ChildPointBalanceParams struct {
	FamilyID pgtype.UUID `json:"family_id"`
	ChildID  pgtype.UUID `json:"child_id"`
}

func (q *Queries) ChildPointBalance(ctx context.Context, arg ChildPointBalanceParams) (int64, error) {
	row := q.db.QueryRow(ctx, childPointBalance, arg.FamilyID, arg.ChildID)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const createFamily = `-- name: CreateFamily :one
INSERT INTO families (name, timezone, week_starts_on)
VALUES ($1, $2, $3)
RETURNING id, name, timezone, week_starts_on, created_at, updated_at
`

type CreateFamilyParams struct {
	Name         string `json:"name"`
	Timezone     string `json:"timezone"`
	WeekStartsOn int16  `json:"week_starts_on"`
}

type CreateFamilyRow struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Timezone     string             `json:"timezone"`
	WeekStartsOn int16              `json:"week_starts_on"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateFamily(ctx context.Context, arg CreateFamilyParams) (CreateFamilyRow, error) {
	row := q.db.QueryRow(ctx, createFamily, arg.Name, arg.Timezone, arg.WeekStartsOn)
	var i CreateFamilyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Timezone,
		&i.WeekStartsOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFamily = `-- name: GetFamily :one
SELECT id, name, timezone, week_starts_on, created_at, updated_at
FROM families WHERE id = $1
`

type GetFamilyRow struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Timezone     string             `json:"timezone"`
	WeekStartsOn int16              `json:"week_starts_on"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetFamily(ctx context.Context, id pgtype.UUID) (GetFamilyRow, error) {
	row := q.db.QueryRow(ctx, getFamily, id)
	var i GetFamilyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Timezone,
		&i.WeekStartsOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveChildren = `-- name: ListActiveChildren :many
SELECT id, family_id, nickname, avatar, color, pin_hash, archived_at, created_at, updated_at
FROM children WHERE family_id = $1 AND archived_at IS NULL ORDER BY nickname
`

func (q *Queries) ListActiveChildren(ctx context.Context, familyID pgtype.UUID) ([]Child, error) {
	rows, err := q.db.Query(ctx, listActiveChildren, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Child{}
	for rows.Next() {
		var i Child
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.Nickname,
			&i.Avatar,
			&i.Color,
			&i.PinHash,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
