// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbgen

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type CompletionDecision string

const (
	CompletionDecisionPending   CompletionDecision = "pending"
	CompletionDecisionWithdrawn CompletionDecision = "withdrawn"
	CompletionDecisionApproved  CompletionDecision = "approved"
	CompletionDecisionRejected  CompletionDecision = "rejected"
	CompletionDecisionCancelled CompletionDecision = "cancelled"
)

func (e *CompletionDecision) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CompletionDecision(s)
	case string:
		*e = CompletionDecision(s)
	default:
		return fmt.Errorf("unsupported scan type for CompletionDecision: %T", src)
	}
	return nil
}

type NullCompletionDecision struct {
	CompletionDecision CompletionDecision `json:"completion_decision"`
	Valid              bool               `json:"valid"` // Valid is true if CompletionDecision is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCompletionDecision) Scan(value interface{}) error {
	if value == nil {
		ns.CompletionDecision, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CompletionDecision.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCompletionDecision) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CompletionDecision), nil
}

type LedgerKind string

const (
	LedgerKindAward            LedgerKind = "award"
	LedgerKindApprovalReversal LedgerKind = "approval_reversal"
	LedgerKindManualCorrection LedgerKind = "manual_correction"
)

func (e *LedgerKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LedgerKind(s)
	case string:
		*e = LedgerKind(s)
	default:
		return fmt.Errorf("unsupported scan type for LedgerKind: %T", src)
	}
	return nil
}

type NullLedgerKind struct {
	LedgerKind LedgerKind `json:"ledger_kind"`
	Valid      bool       `json:"valid"` // Valid is true if LedgerKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLedgerKind) Scan(value interface{}) error {
	if value == nil {
		ns.LedgerKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LedgerKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLedgerKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LedgerKind), nil
}

type MembershipRole string

const (
	MembershipRoleOwner  MembershipRole = "owner"
	MembershipRoleParent MembershipRole = "parent"
)

func (e *MembershipRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MembershipRole(s)
	case string:
		*e = MembershipRole(s)
	default:
		return fmt.Errorf("unsupported scan type for MembershipRole: %T", src)
	}
	return nil
}

type NullMembershipRole struct {
	MembershipRole MembershipRole `json:"membership_role"`
	Valid          bool           `json:"valid"` // Valid is true if MembershipRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMembershipRole) Scan(value interface{}) error {
	if value == nil {
		ns.MembershipRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MembershipRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMembershipRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MembershipRole), nil
}

type OccurrenceState string

const (
	OccurrenceStateNotStarted       OccurrenceState = "not_started"
	OccurrenceStatePendingApproval  OccurrenceState = "pending_approval"
	OccurrenceStateApproved         OccurrenceState = "approved"
	OccurrenceStateApprovalReversed OccurrenceState = "approval_reversed"
	OccurrenceStateCancelled        OccurrenceState = "cancelled"
)

func (e *OccurrenceState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OccurrenceState(s)
	case string:
		*e = OccurrenceState(s)
	default:
		return fmt.Errorf("unsupported scan type for OccurrenceState: %T", src)
	}
	return nil
}

type NullOccurrenceState struct {
	OccurrenceState OccurrenceState `json:"occurrence_state"`
	Valid           bool            `json:"valid"` // Valid is true if OccurrenceState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOccurrenceState) Scan(value interface{}) error {
	if value == nil {
		ns.OccurrenceState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OccurrenceState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOccurrenceState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OccurrenceState), nil
}

type ScheduleKind string

const (
	ScheduleKindDaily    ScheduleKind = "daily"
	ScheduleKindWeekdays ScheduleKind = "weekdays"
	ScheduleKindOneOff   ScheduleKind = "one_off"
)

func (e *ScheduleKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ScheduleKind(s)
	case string:
		*e = ScheduleKind(s)
	default:
		return fmt.Errorf("unsupported scan type for ScheduleKind: %T", src)
	}
	return nil
}

type NullScheduleKind struct {
	ScheduleKind ScheduleKind `json:"schedule_kind"`
	Valid        bool         `json:"valid"` // Valid is true if ScheduleKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullScheduleKind) Scan(value interface{}) error {
	if value == nil {
		ns.ScheduleKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ScheduleKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullScheduleKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ScheduleKind), nil
}

type SessionMode string

const (
	SessionModeShared SessionMode = "shared"
	SessionModeParent SessionMode = "parent"
	SessionModeChild  SessionMode = "child"
)

func (e *SessionMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SessionMode(s)
	case string:
		*e = SessionMode(s)
	default:
		return fmt.Errorf("unsupported scan type for SessionMode: %T", src)
	}
	return nil
}

type NullSessionMode struct {
	SessionMode SessionMode `json:"session_mode"`
	Valid       bool        `json:"valid"` // Valid is true if SessionMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSessionMode) Scan(value interface{}) error {
	if value == nil {
		ns.SessionMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SessionMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSessionMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SessionMode), nil
}

type TaskState string

const (
	TaskStateActive    TaskState = "active"
	TaskStateCancelled TaskState = "cancelled"
)

func (e *TaskState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskState(s)
	case string:
		*e = TaskState(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskState: %T", src)
	}
	return nil
}

type NullTaskState struct {
	TaskState TaskState `json:"task_state"`
	Valid     bool      `json:"valid"` // Valid is true if TaskState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskState) Scan(value interface{}) error {
	if value == nil {
		ns.TaskState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskState), nil
}

type AuditEvent struct {
	ID             pgtype.UUID        `json:"id"`
	FamilyID       pgtype.UUID        `json:"family_id"`
	ActorUserID    pgtype.UUID        `json:"actor_user_id"`
	ActorChildID   pgtype.UUID        `json:"actor_child_id"`
	Action         string             `json:"action"`
	SubjectType    pgtype.Text        `json:"subject_type"`
	SubjectID      pgtype.UUID        `json:"subject_id"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	SessionID      pgtype.UUID        `json:"session_id"`
	BeforeStatus   pgtype.Text        `json:"before_status"`
	AfterStatus    pgtype.Text        `json:"after_status"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
	Reason         pgtype.Text        `json:"reason"`
}

type AuthenticationAttempt struct {
	ID             pgtype.UUID        `json:"id"`
	IdentifierHash []byte             `json:"identifier_hash"`
	SourceHash     []byte             `json:"source_hash"`
	Outcome        string             `json:"outcome"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Child struct {
	ID         pgtype.UUID        `json:"id"`
	FamilyID   pgtype.UUID        `json:"family_id"`
	Nickname   string             `json:"nickname"`
	Avatar     string             `json:"avatar"`
	Color      string             `json:"color"`
	PinHash    pgtype.Text        `json:"pin_hash"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type CompletionAttempt struct {
	ID            pgtype.UUID        `json:"id"`
	FamilyID      pgtype.UUID        `json:"family_id"`
	OccurrenceID  pgtype.UUID        `json:"occurrence_id"`
	ChildID       pgtype.UUID        `json:"child_id"`
	AttemptNumber int32              `json:"attempt_number"`
	Decision      CompletionDecision `json:"decision"`
	SubmittedAt   pgtype.Timestamptz `json:"submitted_at"`
	DecidedAt     pgtype.Timestamptz `json:"decided_at"`
	DecidedBy     pgtype.UUID        `json:"decided_by"`
	DecisionNote  pgtype.Text        `json:"decision_note"`
}

type Family struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	Timezone          string             `json:"timezone"`
	WeekStartsOn      int16              `json:"week_starts_on"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ParentIdleMinutes int16              `json:"parent_idle_minutes"`
}

type FamilyMembership struct {
	FamilyID  pgtype.UUID        `json:"family_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Role      MembershipRole     `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Habit struct {
	ID           pgtype.UUID        `json:"id"`
	FamilyID     pgtype.UUID        `json:"family_id"`
	Title        string             `json:"title"`
	Description  pgtype.Text        `json:"description"`
	Icon         pgtype.Text        `json:"icon"`
	Color        pgtype.Text        `json:"color"`
	ArchivedAt   pgtype.Timestamptz `json:"archived_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	InactiveFrom pgtype.Date        `json:"inactive_from"`
	Version      int64              `json:"version"`
}

type HabitAssignment struct {
	ID                     pgtype.UUID        `json:"id"`
	FamilyID               pgtype.UUID        `json:"family_id"`
	HabitID                pgtype.UUID        `json:"habit_id"`
	ChildID                pgtype.UUID        `json:"child_id"`
	Points                 int32              `json:"points"`
	EffectiveFrom          pgtype.Date        `json:"effective_from"`
	EffectiveUntil         pgtype.Date        `json:"effective_until"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	SupersedesAssignmentID pgtype.UUID        `json:"supersedes_assignment_id"`
	Version                int64              `json:"version"`
}

type HabitSchedule struct {
	AssignmentID pgtype.UUID  `json:"assignment_id"`
	Kind         ScheduleKind `json:"kind"`
	Weekdays     []int16      `json:"weekdays"`
	DueDate      pgtype.Date  `json:"due_date"`
}

type HabitVersion struct {
	ID             pgtype.UUID        `json:"id"`
	FamilyID       pgtype.UUID        `json:"family_id"`
	HabitID        pgtype.UUID        `json:"habit_id"`
	Title          string             `json:"title"`
	Description    pgtype.Text        `json:"description"`
	Icon           pgtype.Text        `json:"icon"`
	Color          pgtype.Text        `json:"color"`
	EffectiveFrom  pgtype.Date        `json:"effective_from"`
	EffectiveUntil pgtype.Date        `json:"effective_until"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type IdempotencyRecord struct {
	ID             pgtype.UUID        `json:"id"`
	FamilyID       pgtype.UUID        `json:"family_id"`
	SessionID      pgtype.UUID        `json:"session_id"`
	RouteFamily    string             `json:"route_family"`
	IdempotencyKey string             `json:"idempotency_key"`
	RequestHash    []byte             `json:"request_hash"`
	ResponseStatus pgtype.Int2        `json:"response_status"`
	ResponseBody   []byte             `json:"response_body"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Occurrence struct {
	ID                  pgtype.UUID        `json:"id"`
	FamilyID            pgtype.UUID        `json:"family_id"`
	AssignmentID        pgtype.UUID        `json:"assignment_id"`
	ChildID             pgtype.UUID        `json:"child_id"`
	LocalDate           pgtype.Date        `json:"local_date"`
	TitleSnapshot       string             `json:"title_snapshot"`
	PointsSnapshot      int32              `json:"points_snapshot"`
	State               OccurrenceState    `json:"state"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	TaskID              pgtype.UUID        `json:"task_id"`
	SourceType          string             `json:"source_type"`
	DueDate             pgtype.Date        `json:"due_date"`
	ItemTypeSnapshot    string             `json:"item_type_snapshot"`
	Version             int64              `json:"version"`
	DescriptionSnapshot string             `json:"description_snapshot"`
	IconSnapshot        string             `json:"icon_snapshot"`
	ColorSnapshot       string             `json:"color_snapshot"`
}

type OneOffTask struct {
	ID                 pgtype.UUID        `json:"id"`
	FamilyID           pgtype.UUID        `json:"family_id"`
	ChildID            pgtype.UUID        `json:"child_id"`
	Title              string             `json:"title"`
	Description        pgtype.Text        `json:"description"`
	Icon               pgtype.Text        `json:"icon"`
	Color              pgtype.Text        `json:"color"`
	Points             int32              `json:"points"`
	DueDate            pgtype.Date        `json:"due_date"`
	State              TaskState          `json:"state"`
	CancellationReason pgtype.Text        `json:"cancellation_reason"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	Version            int64              `json:"version"`
}

type PointLedger struct {
	ID                  pgtype.UUID        `json:"id"`
	FamilyID            pgtype.UUID        `json:"family_id"`
	ChildID             pgtype.UUID        `json:"child_id"`
	OccurrenceID        pgtype.UUID        `json:"occurrence_id"`
	CompletionAttemptID pgtype.UUID        `json:"completion_attempt_id"`
	Kind                LedgerKind         `json:"kind"`
	Amount              int32              `json:"amount"`
	Reason              pgtype.Text        `json:"reason"`
	ActorUserID         pgtype.UUID        `json:"actor_user_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	ReversesEntryID     pgtype.UUID        `json:"reverses_entry_id"`
}

type Session struct {
	ID               pgtype.UUID        `json:"id"`
	FamilyID         pgtype.UUID        `json:"family_id"`
	UserID           pgtype.UUID        `json:"user_id"`
	ActiveChildID    pgtype.UUID        `json:"active_child_id"`
	TokenHash        []byte             `json:"token_hash"`
	Mode             SessionMode        `json:"mode"`
	ParentUnlockedAt pgtype.Timestamptz `json:"parent_unlocked_at"`
	LastActivityAt   pgtype.Timestamptz `json:"last_activity_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	CsrfTokenHash    []byte             `json:"csrf_token_hash"`
}

type User struct {
	ID            pgtype.UUID        `json:"id"`
	Email         string             `json:"email"`
	PasswordHash  string             `json:"password_hash"`
	ParentPinHash pgtype.Text        `json:"parent_pin_hash"`
	Active        bool               `json:"active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}
