// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: occurrences.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOccurrence = `-- name: CreateOccurrence :one
INSERT INTO occurrences
  (family_id, assignment_id, child_id, local_date, title_snapshot, points_snapshot)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (assignment_id, child_id, local_date) DO UPDATE
  SET title_snapshot = occurrences.title_snapshot
RETURNING id, family_id, assignment_id, child_id, local_date, title_snapshot,
          points_snapshot, state, created_at, updated_at
`

type CreateOccurrenceParams struct {
	FamilyID       pgtype.UUID `json:"family_id"`
	AssignmentID   pgtype.UUID `json:"assignment_id"`
	ChildID        pgtype.UUID `json:"child_id"`
	LocalDate      pgtype.Date `json:"local_date"`
	TitleSnapshot  string      `json:"title_snapshot"`
	PointsSnapshot int32       `json:"points_snapshot"`
}

type CreateOccurrenceRow struct {
	ID             pgtype.UUID        `json:"id"`
	FamilyID       pgtype.UUID        `json:"family_id"`
	AssignmentID   pgtype.UUID        `json:"assignment_id"`
	ChildID        pgtype.UUID        `json:"child_id"`
	LocalDate      pgtype.Date        `json:"local_date"`
	TitleSnapshot  string             `json:"title_snapshot"`
	PointsSnapshot int32              `json:"points_snapshot"`
	State          OccurrenceState    `json:"state"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateOccurrence(ctx context.Context, arg CreateOccurrenceParams) (CreateOccurrenceRow, error) {
	row := q.db.QueryRow(ctx, createOccurrence,
		arg.FamilyID,
		arg.AssignmentID,
		arg.ChildID,
		arg.LocalDate,
		arg.TitleSnapshot,
		arg.PointsSnapshot,
	)
	var i CreateOccurrenceRow
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.AssignmentID,
		&i.ChildID,
		&i.LocalDate,
		&i.TitleSnapshot,
		&i.PointsSnapshot,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChildOccurrencesForDate = `-- name: ListChildOccurrencesForDate :many
SELECT id, family_id, assignment_id, child_id, local_date, title_snapshot,
       points_snapshot, state, created_at, updated_at
FROM occurrences
WHERE family_id = $1 AND child_id = $2 AND local_date = $3
ORDER BY created_at, id
`

type ListChildOccurrencesForDateParams struct {
	FamilyID  pgtype.UUID `json:"family_id"`
	ChildID   pgtype.UUID `json:"child_id"`
	LocalDate pgtype.Date `json:"local_date"`
}

type ListChildOccurrencesForDateRow struct {
	ID             pgtype.UUID        `json:"id"`
	FamilyID       pgtype.UUID        `json:"family_id"`
	AssignmentID   pgtype.UUID        `json:"assignment_id"`
	ChildID        pgtype.UUID        `json:"child_id"`
	LocalDate      pgtype.Date        `json:"local_date"`
	TitleSnapshot  string             `json:"title_snapshot"`
	PointsSnapshot int32              `json:"points_snapshot"`
	State          OccurrenceState    `json:"state"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListChildOccurrencesForDate(ctx context.Context, arg ListChildOccurrencesForDateParams) ([]ListChildOccurrencesForDateRow, error) {
	rows, err := q.db.Query(ctx, listChildOccurrencesForDate, arg.FamilyID, arg.ChildID, arg.LocalDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChildOccurrencesForDateRow{}
	for rows.Next() {
		var i ListChildOccurrencesForDateRow
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.AssignmentID,
			&i.ChildID,
			&i.LocalDate,
			&i.TitleSnapshot,
			&i.PointsSnapshot,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
