// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ChildPointBalance(ctx context.Context, arg ChildPointBalanceParams) (int64, error)
	CreateFamily(ctx context.Context, arg CreateFamilyParams) (CreateFamilyRow, error)
	CreateOccurrence(ctx context.Context, arg CreateOccurrenceParams) (CreateOccurrenceRow, error)
	GetFamily(ctx context.Context, id pgtype.UUID) (GetFamilyRow, error)
	ListActiveChildren(ctx context.Context, familyID pgtype.UUID) ([]Child, error)
	ListChildOccurrencesForDate(ctx context.Context, arg ListChildOccurrencesForDateParams) ([]ListChildOccurrencesForDateRow, error)
}

var _ Querier = (*Queries)(nil)
